package com.exceptioncoder.llm.infrastructure.devplan.profile;

import com.exceptioncoder.llm.domain.devplan.exception.ProfileGenerationException;
import com.exceptioncoder.llm.domain.devplan.service.ProfileGenerator;
import com.exceptioncoder.llm.domain.devplan.service.ProfileGeneratorService;
import com.exceptioncoder.llm.infrastructure.devplan.config.DevPlanProfileProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Comparator;
import java.util.List;
import java.util.Optional;

/**
 * 画像生成器编排器 —— 按 order 依次尝试，第一个成功即返回。
 *
 * <p>当 {@code require-llm-generator=true} 时，跳过 {@link ProfileGenerator#isLlmBased()}
 * 为 false 的生成器（如 InternalFallbackGenerator），全部失败直接报错。
 *
 * @author zhangkai
 * @since 2026-04-11
 */
@Slf4j
@Service
public class ProfileGeneratorChain implements ProfileGeneratorService {

    private final List<ProfileGenerator> generators;
    private final DevPlanProfileProperties properties;

    public ProfileGeneratorChain(List<ProfileGenerator> generators,
                                 DevPlanProfileProperties properties) {
        this.generators = generators.stream()
                .sorted(Comparator.comparingInt(ProfileGenerator::order))
                .toList();
        this.properties = properties;
    }

    /**
     * 按优先级依次尝试生成画像，第一个成功即返回。
     *
     * @param projectPath 项目根目录绝对路径
     * @return 生成的 Markdown 内容
     * @throws ProfileGenerationException 所有生成器均失败
     */
    public String generateOrThrow(String projectPath) {
        boolean requireLlm = properties.isRequireLlmGenerator();

        for (ProfileGenerator gen : generators) {
            String name = gen.getClass().getSimpleName();

            if (requireLlm && !gen.isLlmBased()) {
                log.info("ProfileGenerator [{}] skipped: require-llm-generator=true", name);
                continue;
            }
            if (!gen.isAvailable()) {
                log.info("ProfileGenerator [{}] skipped: not available", name);
                continue;
            }

            Optional<String> result = gen.generate(projectPath);
            if (result.isPresent()) {
                log.info("Profile generated by [{}]", name);
                return result.get();
            }
            log.warn("ProfileGenerator [{}] failed, trying next", name);
        }

        String msg = requireLlm
                ? "All LLM-based generators failed (require-llm-generator=true, internal fallback disabled): "
                : "All ProfileGenerators failed for: ";
        throw new ProfileGenerationException(msg + projectPath);
    }
}
